---

- name: Copy systemd unit files
  copy: src="{{ item }}.service" dest="/etc/systemd/system/{{ item }}.service"
  with_items: "{{ kubernetes_master_components }}"

- name: kubernetes_master 
  debug: msg="{{ kubernetes_master }}"

- name: kubernetes_nameserver 
  debug: msg="{{ kubernetes_nameserver }}"

- name: Add environment variables for kubernetes  
  lineinfile: dest='/etc/environment' line="{{ item.key }}={{ item.value }}" state=present create=yes
  with_dict: "{{ env_vars }}"

- name: reload systemd
  shell: systemctl daemon-reload
